apiVersion: apps/v1
kind: Deployment
metadata:
  name: myhp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      securityContext:
        fsGroup: 1001 
      containers:
      - name: con1
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: myvol
          mountPath: /app/
#      - name: con2
#        image: tomcat:latest
#        ports:
#        - containerPort: 8080
#        volumeMounts:
#        - name: myvol
#          mountPath: /app/
      volumes:
      - name: myvol
        hostPath:
          path: /tmp

#
