apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ing-backend
  namespace: default
spec:
  podSelector:
    matchLabels:
      deployment: backend
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          deployment: frontend
