apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: con1
        image: nginx:latest
        ports:
        - containerPort: 80
        resources: 
          requests:
            cpu: "100m"
            memory: "64Mi"
          limits:
            cpu: "1000m"
            memory: "1024Mi"
#        livenessProbe:
#          httpGet:
#            path: /fail
#            port: 80
#          periodSeconds: 5
#          initialDelaySeconds: 10

