apiVersion: v1
kind: Pod
metadata:
 name: mypod
 labels:
   app: myapp
spec:
 containers:
 - name: con1
   image: wordpress:latest
   ports:
   - containerPort: 80
 - name: con2
   image: mysql:5.7
   env:
   - name: MYSQL_ROOT_PASSWORD
     value: test123
   - name: MYSQL_DATABASE
     value: wpdb
   ports:
   - containerPort: 3306

