apiVersion: v1
kind: Secret
metadata:
  name: webhook-user-token
  labels:
     app: nationalparks
  annotations:
    kubernetes.io/service-account.name: webhook-user
type: kubernetes.io/service-account-token

