apiVersion: v1
kind: Pod
metadata:
  labels:
    run: a1
  name: a1
spec:
  containers:
  - image: nginx
    name: a1
    resources:
      requests:
        cpu: 90m
        memory: 128Mi
      limits:
        cpu: 1
        memory: 3Gi
