events {}
http {
  server {
    listen 8443 ssl;
    server_name tlsapp.apps-crc.testing;

    ssl_certificate /etc/nginx/tls/tls.crt;
    ssl_certificate_key /etc/nginx/tls/tls.key;

    location / {
      return 200 "Hello from Passthrough TLS\n";
    }
  }
}
